# .terraform-docs.yml

# https://lalalilala.tistory.com/entry/READMEmd-%EC%9E%91%EC%84%B1-%EC%9E%90%EB%8F%99%ED%99%94-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8-%E2%80%98Terraform-Docs%E2%80%99-%EA%B0%84%EB%8B%A8%EC%86%8C%EA%B0%9C

# 출력 형식 지정
formatter: "markdown table"

# 하위 디렉토리 자동 탐색 설정
recursive:
  enabled: true # 하위 폴더 탐색 기능 활성화
  path: "." # 루트부터 모든 하위 폴더를 탐색
  include-main: true # 루트 폴더에 테람폼 파일 있을 경우 문서화에 포함할지 여부

output:
  file: "README.md" # 생성된 내용 파일명
  mode: inject
